In [1]:
%run module.ipynb
# this already imports the following packages
# import numpy as np
# import pandas as pd  
import pysindy as ps
import matplotlib.pyplot as plt

In this notebook we will explore how the uncertainty of the variables changes as we add more and more data.

In [67]:
# load data
r = np.load('./data/lorenz_r.npy')
r_noisy = np.load("./data/lorenz_r_noisy.npy")
t = np.load("./data/lorenz_t.npy")

# r is shaped like (n_points,n_dimensions)
print("Data vector:")
print(r[:5])

# t is time axis
print("\n\nTime vector:")
print(t[:5])

feature_names = ['x','y','z'] # just a label for the features, instead of simply using x1,x2....

# sampling length
iters = 2000
nr_burnin = 500

opt=SBAM(max_iter=iters,burn_in=nr_burnin,verbose=True)

# setting beta hyperparameters for theta
opt.a=1. 
opt.b=10000000000.

# hyperparameter for tau2
opt.s=0.5

# hyperparameter for sigma2
opt.a1=0.01
opt.a2=0.001

dif = ps.FiniteDifference(order=12)

model = ps.SINDy(feature_names=feature_names,optimizer=opt,differentiation_method=dif)

Data vector:
[[1.         1.         1.        ]
 [1.01256821 1.2599461  0.98488969]
 [1.04883096 1.52405449 0.97311235]
 [1.10722704 1.79839899 0.96515735]
 [1.18690156 2.08866556 0.96173704]]


Time vector:
[0.       0.010001 0.020002 0.030003 0.040004]


In [73]:
list = np.logspace(1.7,4).astype(int)


array([   50,    55,    62,    69,    77,    86,    95,   106,   118,
         132,   147,   164,   183,   204,   227,   253,   282,   314,
         350,   390,   435,   484,   540,   601,   670,   747,   832,
         927,  1033,  1151,  1282,  1429,  1592,  1774,  1976,  2202,
        2453,  2733,  3045,  3393,  3780,  4212,  4692,  5228,  5825,
        6490,  7230,  8056,  8975, 10000])

In [74]:

vars = pd.DataFrame()
for N in list:
    opt=SBAM(max_iter=iters,burn_in=nr_burnin,verbose=True)

    # setting beta hyperparameters for theta
    opt.a=1. 
    opt.b=10000000000.

    # hyperparameter for tau2
    opt.s=0.5

    # hyperparameter for sigma2
    opt.a1=0.01
    opt.a2=0.001

    dif = ps.FiniteDifference(order=12)

    model = ps.SINDy(feature_names=feature_names,optimizer=opt,differentiation_method=dif)
    print("Fitting with {} data points...".format(N))
    model.fit(r_noisy[:N,],t=t[:N])
    
    df=model.optimizer.samples[0] # xdot regression
    vars=vars.append(df['beta'][df['z']==1].var(),ignore_index=True)

Fitting with 50 data points...
Sampling for target n# 0/2...
|████████████████████████████████████████| 1999/1999 [100%] in 9.0s (222.55/s)                                          
Sampling for target n# 1/2...
|████████████████████████████████████████| 1999/1999 [100%] in 9.6s (207.27/s)                                          
Sampling for target n# 2/2...
|████████████████████████████████████████| 1999/1999 [100%] in 8.9s (223.61/s)                                          
Fitting with 55 data points...
Sampling for target n# 0/2...
|████████████████████████████████████████| 1999/1999 [100%] in 15.3s (131.05/s)                                         
Sampling for target n# 1/2...
|████████████████████████████████████████| 1999/1999 [100%] in 7.7s (258.01/s)                                          
Sampling for target n# 2/2...
|████████████████████████████████████████| 1999/1999 [100%] in 11.9s (168.24/s)                                         
Fitting with 62 data points...
S

In [81]:
renaming={key:value for (key,value) in zip(vars.columns,model.get_feature_names())}
vars.rename(columns=renaming,inplace=True)

In [82]:
vars

1             x             y             z           x^2  \
0   1.303703e-01  2.510700e-02  6.506197e-03  1.360049e-01  1.849772e-04   
1   5.644826e-02  1.789882e-03  8.456946e-04  5.685033e-02  5.679299e-06   
2   8.705748e-02  1.386852e-02  3.790951e-03  9.401215e-02  2.800675e-05   
3   5.005290e-03  2.253281e-03  3.086049e-04  3.121443e-03  2.582111e-06   
4   3.500540e-02  1.473469e-01  2.642656e-02  4.921246e-03  1.731321e-04   
5   3.985661e-03  2.889136e-02  4.323189e-03  1.986708e-03  4.301956e-05   
6   6.748128e-04  3.418338e-03  5.479392e-04  3.420574e-04  3.152309e-06   
7   7.824284e-04  1.430297e-03  2.024189e-04  1.414120e-04  1.687415e-06   
8   6.376686e-04  2.832419e-03  4.616361e-04  2.414023e-04  3.522150e-06   
9   9.449072e-04  4.426721e-03  5.979357e-04  4.166803e-04  4.589195e-06   
10  1.697603e-03  1.397604e-03  1.716229e-04  1.425317e-04  1.504352e-06   
11  3.046765e-04  6.623794e-02  9.666107e-03  6.375820e-03  1.016610e-04   
12  5.605299e-05  1.668984e-04  2.449165e-05  1.252245e-05  1.725895e-07   
13  6.874895e-05  3.465875e-04  5.812906e-05  1.014233e-05  2.231027e-07   
14  3.217155e-05  8.403805e-05  1.265841e-05  6.697952e-06  9.951938e-08   
15  4.105799e-05  8.128870e-05  1.549139e-05  6.031290e-06  1.456635e-07   
16  1.636909e-05  3.304797e-05  4.996388e-06  2.413546e-06  3.741141e-08   
17  4.676570e-05  8.836867e-04  3.540757e-04  5.111679e-05  3.686773e-06   
18  4.416814e-05  5.865858e-05  8.960456e-06  7.697213e-06  1.804747e-07   
19  4.627744e-06  9.294548e-06  1.400678e-06  7.159438e-07  1.077279e-08   
20  6.994156e-06  8.900167e-06  1.213420e-06  7.498597e-07  9.736563e-09   
21  3.477530e-06  6.765600e-06  1.138478e-06  4.717654e-07  8.182794e-09   
22  1.838927e-06  4.382836e-06  6.680485e-07  3.544786e-07  5.253539e-09   
23  3.378762e-06  7.378530e-06  1.115339e-06  4.012120e-07  1.320905e-08   
24  1.066352e-06  2.271833e-06  3.695395e-07  1.570802e-07  2.329094e-09   
25  8.339621e-07  1.024597e-06  1.659357e-07  8.282568e-08  1.393762e-09   
26  5.039620e-07  5.826553e-07  1.005011e-07  4.367584e-08  7.781835e-10   
27  4.060927e-07  3.511512e-07  6.329698e-08  2.910885e-08  5.262561e-10   
28  2.366117e-07  1.765201e-07  3.363372e-08  1.497183e-08  2.656197e-10   
29  1.620850e-07  9.320221e-08  1.864584e-08  9.144933e-09  1.820501e-10   
30  1.180130e-07  3.519473e-08  8.367129e-09  3.508040e-09  6.962248e-11   
31  6.455400e-08  1.178893e-08  3.735215e-09  1.796715e-09  3.653935e-11   
32  5.980310e-08  8.442275e-09  2.737320e-09  1.434868e-09  2.826566e-11   
33  4.801253e-08  5.160189e-09  1.750058e-09  9.161439e-10  2.125804e-11   
34  2.660907e-08  2.350655e-09  9.290165e-10  6.425656e-10  1.286833e-11   
35  2.380799e-08  1.648551e-09  6.568992e-10  6.400282e-10  1.327736e-11   
36  2.199867e-08  1.202418e-09  5.150305e-10  4.882899e-10  8.707021e-12   
37  1.561691e-08  9.272049e-10  3.926947e-10  3.450149e-10  1.126965e-12   
38  4.004447e-09  6.816888e-10  2.801821e-10  8.977181e-11  0.000000e+00   
39  2.329417e-08  5.479779e-10  2.309104e-10  3.353686e-10  6.864688e-12   
40  5.224832e-09  4.880050e-10  2.079148e-10  1.437935e-10  3.224299e-12   
41  4.460880e-09  3.768611e-10  1.568306e-10  1.268501e-10  3.805685e-12   
42  3.730269e-09  2.848763e-10  1.223266e-10  8.157924e-11  0.000000e+00   
43  0.000000e+00  2.257085e-10  9.980452e-11  0.000000e+00  0.000000e+00   
44  0.000000e+00  1.683414e-10  7.285767e-11  0.000000e+00  0.000000e+00   
45  0.000000e+00  1.342259e-10  6.036912e-11  0.000000e+00  0.000000e+00   
46  0.000000e+00  1.128773e-10  4.973275e-11  0.000000e+00  0.000000e+00   
47  0.000000e+00  9.326006e-11  4.282515e-11  0.000000e+00  0.000000e+00   
48  0.000000e+00  6.679911e-11  2.865200e-11  0.000000e+00  0.000000e+00   
49  0.000000e+00  6.043070e-11  2.650465e-11  0.000000e+00  0.000000e+00   

             x y           x z           y^2           y z           z^2  \
0   7.958390e-05  2.522274e-04  8.339381e-05  1.439610e-05  1.

In [83]:
%matplotlib tk
vars=vars.fillna(0)
vars['N']=list
vars.plot(x='N',logx=True,logy=True,ylabel='Variance',title='$\dot{x}$ Coefficients')
plt.suptitle("Lorenz system")

Text(0.5, 0.98, 'Lorenz system')